### ISSUE TITLE
Reporte de Mockup WebFood

### ISSUE THREAD

**Issue by Arlet04** [SistemasTecTlaxiaco/actividad-5-diseno-de-mockup-para-dapp-mana#1]
[PRACTICA_2_Equipo_Mana.pdf](https://github.com/SistemasTecTlaxiaco/actividad-5-diseno-de-mockup-para-dapp-mana/files/14727725/PRACTICA_2_Equipo_Mana.pdf)

**Comment by ka194** [comment]
Portada: 25
Procedimiento : 25
Figuras, ilustraciones y fotografías.: 25
Resultados y conclusiones: 25
calificación:  20/20  👌👌👌👌👌👌

**Comment by josealfredo79** [comment]
bien hecho y revisado...
